update scripts, justfile, publish*.yml

diff --git a/src/bin/anacron/buildo-anacron-run b/src/bin/anacron/buildo-anacron-run
--- a/src/bin/anacron/buildo-anacron-run
+++ b/src/bin/anacron/buildo-anacron-run
@@ -1,41 +1,41 @@
 #!/bin/bash
 
 # shellcheck disable=SC1091
-source  /usr/lib/buildo/buildo-init
+source /usr/lib/buildo/buildo-init
 
 usage() {
-  echo "Usage: $(basename "$0") [-h] [-n] [-p name]"
-  echo "  -n  use network profile (call my-network-profile)"
-  echo "  -p name  specify profile name (default: current user name)"
+    echo "Usage: $(basename "$0") [-h] [-n] [-p name]"
+    echo "  -n  use network profile (call my-network-profile)"
+    echo "  -p name  specify profile name (default: current user name)"
 }
 profile_name=$(whoami)
 check_network_profile=false
 while getopts "hnp:" arg; do
-  case $arg in
-  h)
-    usage
-    exit 0
-    ;;
-  n)
-    check_network_profile=true
-    ;;
-  p)
-    profile_name="$OPTARG"
-    ;;
-  *)
-    usage
-    exit 1
-    ;;
-  esac
+    case $arg in
+    h)
+        usage
+        exit 0
+        ;;
+    n)
+        check_network_profile=true
+        ;;
+    p)
+        profile_name="$OPTARG"
+        ;;
+    *)
+        usage
+        exit 1
+        ;;
+    esac
 done
 shift $((OPTIND - 1))
 if [[ $# -ne 0 ]]; then
-  usage
-  exit 0
+    usage
+    exit 0
 fi
 
 readonly anacrontab_home=$BUILDO_HOME/anacrontab
-working_home=$(buildo-config .anacron.working-home )
+working_home=$(buildo-config .anacron.working-home)
 working_home=${working_home:-$HOME/.buildo-anacron}
 readonly log_file="$working_home/execution.log"
 
@@ -44,37 +44,37 @@ mkdir -p "$working_home"
 ds=$(date +'%Y%m%d %H:%M:%S %N')
 
 if $check_network_profile; then
-  network_profile_bin=$(buildo-config .anacron.network-profile-bin )
-  network_profile=$("$network_profile_bin")
-  if [[ -n $network_profile ]]; then
-      profile_name="${profile_name}-${network_profile}"
-  else
-      profile_name="${profile_name}-unknown"
-  fi
+    network_profile_bin=$(buildo-config .anacron.network-profile-bin)
+    network_profile=$("$network_profile_bin")
+    if [[ -n $network_profile ]]; then
+        profile_name="${profile_name}-${network_profile}"
+    else
+        profile_name="${profile_name}-unknown"
+    fi
 fi
 
 readonly spool_directory="$working_home/spool"
 readonly anacrontab="$anacrontab_home/$profile_name"
 
 if [[ ! -f $anacrontab ]]; then
-  echo.error "anacrontab: $anacrontab: not found."
-  echo "${ds} $anacrontab: not found">>"$log_file"
-  exit 2
+    echo.error "anacrontab: $anacrontab: not found."
+    echo "${ds} $anacrontab: not found" >>"$log_file"
+    exit 2
 fi
 
 mkdir -p "$spool_directory" || {
-  echo "Failed to create directory $spool_directory"
-  echo "${ds} $anacrontab Failed to create directory $spool_directory">>"$log_file"
-  exit 1
+    echo "Failed to create directory $spool_directory"
+    echo "${ds} $anacrontab Failed to create directory $spool_directory" >>"$log_file"
+    exit 1
 }
 (
-  set -x
-  anacron -s -t "$anacrontab" -S "$spool_directory"
+    set -x
+    anacron -s -t "$anacrontab" -S "$spool_directory"
 )
 
-anacron_chown=$(buildo-config '.anacron.chown' )
+anacron_chown=$(buildo-config '.anacron.chown')
 if [[ -n $anacron_chown ]]; then
-  chown --changes -R "$anacron_chown" "$spool_directory"
+    chown --changes -R "$anacron_chown" "$spool_directory"
 fi
 
-echo "${ds} $anacrontab">>"$log_file"
+echo "${ds} $anacrontab" >>"$log_file"
